scratch-org-def: config/project-scratch-def.json
assign-permset: true
permset-name: TheWizardApp
run-apex-tests: false
delete-scratch-org: false
show-scratch-org-url: true
generate-password: true
data-import:
  - data/masterImportPlan.json
